use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'TBPerformanceView_Example' do
  pod 'TBPerformanceView', :path => '../'
  pod 'SDWebImage'
  pod 'TBToolCategory'
  target 'TBPerformanceView_Tests' do
    inherit! :search_paths

    
  end
end
